# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f434e1927e4962e42366ebd83aabfca00c5315add47bfb3fcd79f192867411a57ec89b4e6fe4568372f3bd77f85105f1147b4369759f859d69d7ad93197a3d

test:
  secret_key_base: 9087776712e9397e95f2dd5794f38d7b44523d670f6b6896a7fffc81d86965afc7da3457937847236f596bd8134f47bf51af023dbcdda6ebb309a901b25c7f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
